apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::693431411908:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::693431411908:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-S86TDOZSPJW2
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-10-20T07:22:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "52254"
  uid: 17d7e99c-7448-469a-96d6-8e94f0b08d2a
