apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::693431411908:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-D938KUWOOAG6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::693431411908:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2021-10-24T09:01:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1066"
  uid: a721e5a6-504b-4669-a369-b69763ee8e23
